version: "3.8"

services:
  volleyvision:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data/processed:/app/data/processed
    environment:
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY}
    restart: unless-stopped